# Generated by Django 3.2.8 on 2021-10-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_auto_20211024_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='test@yahoo.com', max_length=254),
            preserve_default=False,
        ),
    ]
